# .gitlab-ci.yml

image: gradle:alpine

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/
    - build/

before_script:
  - chmod +x ./gradlew
  - echo "Using GRADLE_USER_HOME=$GRADLE_USER_HOME"

build:
  stage: build
  script:
    - ./gradlew --no-daemon clean build-cs108
  artifacts:
    paths:
      - build/libs/*.jar
      - build/docs/javadoc/
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew --no-daemon check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/*.xml
    paths:
      - build/reports/tests/
    expire_in: 2 days

deploy:
  stage: deploy
  script:
    - echo "📦 Deploying"
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
