# .gitlab-ci.yml

image: gradle:7.6-jdk21

stages:
  - build
  - test
  - deploy

variables:
  # Persist Gradle cache inside project
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/
    - build/

before_script:
  - echo "Using GRADLE_USER_HOME=$GRADLE_USER_HOME"

build:
  stage: build
  script:
    # Your custom task that builds both JAR and Javadoc
    - gradle --no-daemon --build-cache build-cs108
  artifacts:
    paths:
      # Your fat jar(s) land here
      - build/libs/*.jar
      # Javadoc directory
      - build/docs/javadoc/
    expire_in: 1 week

test:
  stage: test
  script:
    # Run all checks (compilation + tests)
    - gradle --no-daemon --build-cache check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/*.xml
    paths:
      # HTML test reports (optional)
      - build/reports/tests/

deploy:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - echo "Deploy step – replace with your upload/publish commands"
    # e.g. scp build/libs/*-fat.jar user@server:/opt/apps/
  environment: production
  only:
    - main
